### PR TITLE
RestrictedFunctionsSniff: Add add_site_option function to site_option

### LINKED ISSUE #370: add_site_option in RestrictedFunctions grouping
## What problem would the enhancement address for VIP?

Add `add_site_option()` to the RestrictedFunctions sniff, as we already have `update_site_option()` and `delete_site_option()` for consistent grouping.  We'll also need to silence it on the WordPress-VIP-Go ruleset.

## What code should be reported as a violation?

```php
add_site_option( 'blahblah' );
```

## What could should *not* be reported as a violation?

```php
add_option();
```

### PR DESCRIPTION
**Pull request by rebeccahum**
Fixes #370.

### CODE REVIEW

**Comment by rebeccahum** [comment]
I don't think so because that grouping of rules isn't explicitly listed in the `WordPressVIPMinimum` ruleset.

**Comment by GaryJones** [comment]
> I don't think so because that grouping of rules isn't explicitly listed in the `WordPressVIPMinimum` ruleset.

They may be implicitly included by virtue of the whole directory of sniffs being included, but that doesn't mean we shouldn't be testing for them. There are plenty of `// WordPressVIPMinimum.` instances in the ruleset test, including a [whole block](https://github.com/Automattic/VIP-Coding-Standards/blob/master/WordPressVIPMinimum/ruleset-test.inc#L120) for RestrictedFunctions; though it looks incomplete, any new additions should be added anyway IMO.

**Comment by rebeccahum** [comment]
If we are going to test for them, we should test for all being implicitly included and re-work the WordPressVIPMinimum integration tests to account for that in a different PR.

**Comment by GaryJones** [comment]
> If we are going to test for them, we should test for all being implicitly included and re-work the WordPressVIPMinimum integration tests to account for that in a different PR.

Right - the ruleset test needs updating in another PR, but the bit relevant to this PR should be added in this PR - think atomic commits / merges.

**Comment by rebeccahum** [comment]
Fair enough, done!

**Pull request merged**
